### ISSUE TITLE
Issues building db [bl4.1.1]

### ISSUE THREAD

**Issue by schroef** [Thicket-Blender/thicket#58]
**Describe the bug**
This is a "silent" error as its only seen in the console. Im seeing json or db creation errors. My guess its because of the changes done to the lbw.gz files and how they are structered. I have some old version on an USB drive. But with the latest plantkit as a test. Im see these errors in the console. 

```
Traceback (most recent call last):
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 390, in <module>
    main()
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 383, in main
    ThicketDB.parse_model_json(args.f)
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 337, in parse_model_json
    m_rec = ThicketDB.parse_model(filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 317, in parse_model
    preview_path = Path(filepath).parent.absolute() / "models" / (preview_stem + "_" + v.name + ".png")
                                                                                       ^^^^^^
AttributeError: 'ModelVariant' object has no attribute 'name'
Traceback (most recent call last):
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 390, in <module>
    main()
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 383, in main
Traceback (most recent call last):
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 390, in <module>
    ThicketDB.parse_model_json(args.f)
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 337, in parse_model_json
    main()
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 383, in main
    m_rec = ThicketDB.parse_model(filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ThicketDB.parse_model_json(args.f)
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 317, in parse_model
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 337, in parse_model_json
    preview_path = Path(filepath).parent.absolute() / "models" / (preview_stem + "_" + v.name + ".png")
                                                                                       ^^^^^^
    m_rec = ThicketDB.parse_model(filepath)
AttributeError: 'ModelVariant' object has no attribute 'name'
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 317, in parse_model
    preview_path = Path(filepath).parent.absolute() / "models" / (preview_stem + "_" + v.name + ".png")
                                                                                       ^^^^^^
AttributeError: 'ModelVariant' object has no attribute 'name'
[debug] Failed to parse 'C:\Program Files\Laubwerk\Plants\Aquilegia_coerulea_'McKana'\Aquilegia_coerulea_'McKana'.lbw.gz' with the JSON parser. Falling back to XML parser.
[debug] Failed to parse 'C:\Program Files\Laubwerk\Plants\Cenchrus_alopecuroides_'Hameln'\Cenchrus_alopecuroides_'Hameln'.lbw.gz' with the JSON parser. Falling back to XML parser.
Traceback (most recent call last):
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 390, in <module>
[debug] Failed to parse 'C:\Program Files\Laubwerk\Plants\Cytisus_scoparius\Cytisus_scoparius.lbw.gz' with the JSON parser. Falling back to XML parser.    main()

  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 383, in main
    ThicketDB.parse_model_json(args.f)
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 337, in parse_model_json
    m_rec = ThicketDB.parse_model(filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 317, in parse_model
    preview_path = Path(filepath).parent.absolute() / "models" / (preview_stem + "_" + v.name + ".png")
[debug]                                                                                        ^^^^^^
Failed to parse 'C:\Program Files\Laubwerk\Plants\Buddleja_davidii_'Pablo_Purple'\Buddleja_davidii_'Pablo_Purple'.lbw.gz' with the JSON parser. Falling back to XML parser.
AttributeError: 'ModelVariant' object has no attribute 'name'
Traceback (most recent call last):
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 390, in <module>
    main()
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 383, in main
    ThicketDB.parse_model_json(args.f)
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 337, in parse_model_json
    m_rec = ThicketDB.parse_model(filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 317, in parse_model
    preview_path = Path(filepath).parent.absolute() / "models" / (preview_stem + "_" + v.name + ".png")
                                                                                       ^^^^^^
Traceback (most recent call last):
AttributeError: 'ModelVariant' object has no attribute 'name'
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 390, in <module>
    main()
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 383, in main
    ThicketDB.parse_model_json(args.f)
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 337, in parse_model_json
    m_rec = ThicketDB.parse_model(filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 317, in parse_model
    preview_path = Path(filepath).parent.absolute() / "models" / (preview_stem + "_" + v.name + ".png")
                                                                                       ^^^^^^
AttributeError: 'ModelVariant' object has no attribute 'name'
Traceback (most recent call last):
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 390, in <module>
    main()
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 383, in main
    ThicketDB.parse_model_json(args.f)
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 337, in parse_model_json
    m_rec = ThicketDB.parse_model(filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 317, in parse_model
    preview_path = Path(filepath).parent.absolute() / "models" / (preview_stem + "_" + v.name + ".png")
                                                                                       ^^^^^^
AttributeError: 'ModelVariant' object has no attribute 'name'
[debug] Failed to parse 'C:\Program Files\Laubwerk\Plants\Acer_campestre\Acer_campestre.lbw.gz' with the JSON parser. Falling back to XML parser.
Traceback (most recent call last):
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 390, in <module>
    main()
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 383, in main
    ThicketDB.parse_model_json(args.f)
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 337, in parse_model_json
    m_rec = ThicketDB.parse_model(filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\romboutversluijs\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\player-for-blender-main\thicket_db.py", line 317, in parse_model
    preview_path = Path(filepath).parent.absolute() / "models" / (preview_stem + "_" + v.name + ".png")
                                                                                       ^^^^^^
```
**To Reproduce**
1. Import thicket add
2. Enable addon
3. Press rebuild DB button

**Expected behavior**
Correct build of the db in form of a JSON file

**Screenshots**
![iss caused by using differe script path](https://github.com/Thicket-Blender/thicket/assets/6923008/68aee94a-20c8-4d1b-b293-7c7c1edb461b)
![Screenshot 2024-07-05 115545](https://github.com/Thicket-Blender/thicket/assets/6923008/80aaa6e5-5277-4f75-a37e-b8b9331f721a)

**Desktop (please complete the following information):**
 -WIN
 - 11 home 24H2
 - bl 4.1.1

**Additional context**
I tried check if i could get the name variant. But using v['name'] doesnt work, item is not subscriptable. name is an attrib name so perhaps it should be stored

**Comment by dvhart** [comment]
Thanks for the report @schroef . Unfortunately, I no longer have current Laubwerk API documentation. The Laubwerk folks have created a fork of Thicket and have been working towards getting it working again (I have not tried it myself). I have been meaning to mark Thicket as Archived for this reason and just have not got around to it. I’ll do that now. Consider trying Laubwerk’s fork of Thicket:

https://github.com/Laubwerk/player-for-blender

**Comment by dvhart** [comment]
Due to changes in the Laubwerk API and the lack of current API documentation, I am no longer able to develop or maintain Thicket. Consider trying Laubwerk’s fork of thicket:

https://github.com/Laubwerk/player-for-blender

Thank you for using Thicket, it was a lot of fun to develop.
